name: hello world
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "welcome to github action course"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: test
        run: echo "yes"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
     - name: deploy
       run: echo "deploy"

  html:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: print html
        run: cat index.html
  
    
  
